version: '3'
services:
    web:
        image: com.codecons.qapass:dev
        restart: always
        environment:
            APP_SECRET: ${APP_SECRET}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 8080:3000
        volumes:
            - .:/usr/src/app
        depends_on:
            - mysql
        networks:
            - qapass
    mysql:
        image: mysql:5.7.25
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 33061:3306
        networks:
            - qapass

networks:
    qapass:
