version: '3'

services:

    app:
        image: codecons:prod
        restart: always
        container_name: code_cons_app
        environment:
            APP_ENV: production
            APP_SECRET: codeconssecret
            APP_RUN: dist
            TZ: Europe/Zagreb
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USERNAME: codecons
            DB_PASSWORD: codecons
            DB_DATABASE: codecons
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:3000
        depends_on:
            - mysql
        networks:
            - zadatak0

    mysql:
        image: mysql:5.7.25
        restart: always
        container_name: code_cons_mysql
        environment:
            MYSQL_ROOT_PASSWORD: codecons
            MYSQL_DATABASE: codecons
            MYSQL_USER: codecons
            MYSQL_PASSWORD: codecons
        ports:
            - 33061
        networks:
            - zadatak0

networks:
    zadatak0:
