version: '3'

services:

  app:
    image: codecons:dev
    restart: always
    container_name: code_cons_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      zadatak0:
        aliases:
          - app

  mysql:
      image: mysql:5.7.25
      restart: unless-stopped
      container_name: code_cons_mysql
      environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
          - 33061:3306
      networks:
          zadatak0:
              aliases:
                  - ${DB_HOST}

networks:
  zadatak0:
