version: '3'
services:
    web:
        image: com.codecons.qapass:prod
        restart: always
        environment:
            APP_SECRET: codeconssecret
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:3000
        depends_on:
            - mysql
        networks:
            - qapass

    mysql:
        image: mysql:5.7.25
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: codecons
            MYSQL_DATABASE: codecons
            MYSQL_USER: codecons
            MYSQL_PASSWORD: codecons
        ports:
            - 33061
        networks:
            - qapass

networks:
    qapass:
