version: '3'
services:
    web:
        image: com.codecons.qapass:prod
        restart: always
        environment:
            APP_ENV: production
            APP_SECRET: codeconssecret
            APP_RUN: dist
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USERNAME: codecons
            DB_PASSWORD: codecons
            DB_DATABASE: codecons
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:3000
        depends_on:
            - mysql
        networks:
            - qapass

    mysql:
        image: mysql:5.7.25
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: codecons
            MYSQL_DATABASE: codecons
            MYSQL_USER: codecons
            MYSQL_PASSWORD: codecons
        ports:
            - 33061
        networks:
            - qapass

networks:
    qapass:
